In [1]:
# 1.データエンジニアの役割(2, 5.0%)

# Pythonの得意とする分野
# サーバ系ツール
# Webシステムの構築
# IoTデバイスの操作
# 3Dグラフィックス

# Pythonの苦手とする分野
# Webアプリなどのフロントエンド
# デスクトップGUI
# 速度向上などのための低レイヤー処理
# 超大規模かつミッションクリティカルな処理

# Python以外の選択肢
# R言語,Excel,VBA,Java

# データサイエンティストとは
# 数学、情報工学、対象分野の専門知識(ドメイン知識)、データ分析またはデータ解析の一連の処理及び理解・評価を行える立場の職種

# データサイエンティストの役割
# モデルやアルゴリズムの構築
# 新たな解法や新技術への取り組み(研究分野)
# 解決したい課題に向き合う実務(実務)
# データとの向き合い方の提示
# 分析結果の評価

# 機械学習以外の選択肢
# ルールベース(if文)
# ルールベースではプログラミングの条件分岐の要領でデータを容易にルール化できるが、パラメータの数が増えると記述が困難になる。
#　統計的手法
# 機械学習と非常に親和性の高いアプローチ

# 教師あり学習
# 正解ラベルがある(目的変数)　⇄　説明変数(特徴データ、特徴量)
# 回帰(目的変数が連続値) Ex.売り上げ、気温
# 分類(目的変数が離散値) Ex.二値分類、多値分類

# 教師なし学習
# 正解ラベルなし
# クラスタリング(グルーピングしてデータ間の相関を見つける)
# 次元削減(大量なデータの種類(説明変数の次元数)をより少ないデータの種類(次元数)で言い表す)
# 主成分分析などを用いて計算しやすい数まで説明変数を減らす

# 強化学習
# ブラックボックス的な環境の中で行動するエージェントが、得られる報酬を最大化するような状態に応じた行動を学習していく

# 学習プロセス
# ハイパーパラメータ(各アルゴリズムの実行に必要なパラメータ)の設定

# パッケージ

# Jupyter Notebook
# 実行した結果は.ipynb拡張子で内部をJSONで保持

# Numpy(数値計算、配列や行列を効率よく扱える)
# 内部はC言語で高速

# Pandas(Numpyを基盤としたDataFrame構造)
# R言語のデータフレームからインスパイア

# Scipy(科学技術計算)
# scikit-learnの内部で高度な計算処理に多用
# 高度な統計処理や線形代数を扱えたり、フーリエ変換などの処理


In [11]:
# 2.Pythonと環境(5, 12.5%)

# venv環境の作成
# python3.6 -m venv 仮想環境名
# venv環境の削除
# rm -rf 仮想環境名

# pipコマンド
# pip uninstall (-y) パッケージ名
# pip install -U パッケージ名(最新版のパッケージをインストール)
# pip list -o(新しいバージョンのあるパッケージ一覧)
# pip freeze > requirements.txt
# pip install -r requirements.txt

# Pythonの基礎

# コーディング規約(PEP8)
# pycodestyle(PEP8のチェックツール)
# Flake8(論理的なチェック(定義したが使用していない変数、importして使用していないモジュール))

# IPythonの特徴
# オブジェクトの後ろに？を付けると、オブジェクトの説明を表示
# %ではじまるマジックコマンド(Ex. %timeit, %%timeit)
# !でよるシェルコマンドの実行

# 基本文法

# []はリスト内包　⇄　{}はセット内包
# {}&key:valueで辞書内表記
names = ['spam', 'ham', 'eggs']
{name: len(name) for name in names}

'Hello Python'

In [12]:
# ジェネレーター式
g = (x*x for x in range(10000))
type(g)
next(g), next(g), next(g)

(0, 1, 4)

In [13]:
s1 = 'hello python'
s1.title()

'Hello Python'

In [14]:
s2 = ' spam  ham       eggs        '
s2.split() # 文字列の空白部分で分割

['spam', 'ham', 'eggs']

In [16]:
s2.strip() # 左右の空白文字を削除

'spam  ham       eggs'

In [ ]:
# pickleモジュール
# Pythonのオブジェクトを直列化してファイルなどで読み書きできるようになる

# デフォルトではログレベルはWARINING(警告)以上が出力される

In [3]:
# 3.数学の基礎(6, 15.0%)

# 「積集合」 2つの集合の共通部分
# 「和集合」 全部

# 指数関数
# 関数の入力が別の数字の肩に乗って使われる関数
# シグモイド関数(0, 0.5)
# xが大きくなると1に近づき、小さくなると0に近づく

# 対数関数(0, 1)
# 入力された値が、底の何乗に相当するかを出力する
# 「自然対数」 底がネイピア数の時
# 「常用対数」 底が10の時
# 1の対数は0

# 三角関数
# sin 「サイン」 = 正弦,垂直方向
# cos 「コサイン」 = 余弦 ,水平方向
# tan「タンジェント」 = 正接
# 「弧度法」 = 1周を2πとする単位(ラジアン)

# 双曲線関数
# sinhx 「ハイパボリックサイン」
# coshx 「ハイパボリックコサイン」 ,懸垂線やカテナリー曲線
# tahnx = sinhx / coshx

# 線形代数

# ベクトル
# 丸括弧で数をまとめて表現したもの
# スカラー
# 単なる一つの数
# ノルム
# ベクトルの大きさをスカラーで表現する時
# ユークリッド距離(2乗和の平方根)
# マンハッタン距離(絶対値の距離)

# 行列
# 行列の掛け算は順番を入れ替えると同じになるとは限らない

# 微分と積分

# 積分
# 積分の記号はインテグラル 
# 「定積分」 = 積分の範囲が決まっている
# 「不定積分」 = 積分の範囲が決まっていない
# Fをfの原始関数、fをFの導関数
# Cは積分定数=オマケ
# f(x) = e^x（eのx乗）は微分してもe^xとなり形が変わらない。これは底がeのときだけ成り立つものであり、ネイピア数を底とする指数関数が解析学で重要な役割を果たす理由の一つである。
# 「微分係数」 = 導関数に具体的なxの値を代入して得られる値
# 最適化は、関数の最小値や、少なくとも局所的な最小値である極小値を求めることを目標としている

# 「共分散」 = それぞれの変数について平均値との差を掛け算する、必ずしも正にならない
# 「相関係数」 = 「ピアソンの積率相関係数」 = 共分散を2つの変数の標準偏差で割った値、-1~1の値をとる
# スピアマンの順位相関係数が有名、ギリシャ文字のローで表現される
# 「確率質量関数」 = 確率変数が離散的
# 「確率密度関数」 = 確率変数が連続的
# 正規分布
# x = 0で最も高い値、左右対象の釣鐘型
# 標準正規分布
# 平均0、分散1

In [2]:
# 4-1.Numpy(6, 15.0%)

# 配列や行列を効率よく扱える
# 配列用の型であるndarrayと行列用の型であるmatrix

numpy.ndarray

In [3]:
import numpy as np

a = np.array([1, 2, 3])
type(a) # オブジェクトの確認

numpy.ndarray

In [4]:
a.shape # 要素数

(3,)

In [6]:
c2 = np.array([[0, 1, 2], [3, 4, 5]])
c3 = c2.ravel() # 参照(浅いコピー)を返す
c3

array([0, 1, 2, 3, 4, 5])

In [7]:
c4 = c2.flatten() # コピー(深いコピー)を返す
c4

# Pythonの標準のスライスはコピーを返すが、Numpyのスライスは参照を返す

array([0, 1, 2, 3, 4, 5])

In [8]:
# データ型
a.dtype　# デフォルトはnp.int64

dtype('int64')

In [11]:
d = np.array([1, 2], dtype=np.int16)
d.dtype

dtype('int16')

In [12]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [14]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b[:, [0, 2]] # 列の値を2つ取得

array([[1, 3],
       [4, 6]])

In [16]:
# 数列を返す(arange)
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# 乱数
np.random.random((3,2)) # 0以上1未満の乱数、タプルで渡す

array([[0.58996137, 0.40919433],
       [0.25533108, 0.42105015],
       [0.40344491, 0.39151405]])

In [18]:
np.random.rand(4, 2) # (行, 列)

array([[0.61495071, 0.87066617],
       [0.67060841, 0.97417483],
       [0.44191833, 0.72573738],
       [0.27541611, 0.94302474]])

In [22]:
np.random.randint(1, 10, (3,3)) # 第三引数としてタプルで渡した行と列の二次元配列を生成

array([[2, 5, 4],
       [2, 5, 2],
       [4, 9, 1]])

In [23]:
np.random.uniform(0.0, 5.0, size=(2, 3))
# 省略すると第一引数は0.0、第二引数は1.0、戻り値は小数値になる

array([[4.02450441, 1.90461414, 4.71917166],
       [3.94617803, 2.55384088, 3.58548407]])

In [24]:
np.random.uniform(size=(4, 3))

array([[0.19416114, 0.09077176, 0.55750109],
       [0.82631612, 0.15634289, 0.93674716],
       [0.0075883 , 0.95631677, 0.22503492],
       [0.24282326, 0.87021213, 0.43778568]])

In [25]:
np.random.randn(4, 2) # 正規分布乱数(標準正規分布(平均0,平均1)の乱数)を生成 ⇄ 一様乱数

array([[ 0.75071375,  0.00189348],
       [ 0.38073252,  0.24036409],
       [ 0.8241902 , -1.20805645],
       [ 1.25815137, -0.90560778]])

In [26]:
# np.random.normal(平均, 標準偏差, size=(x, y)) の正規分布乱数

In [27]:
# 単位行列 = 対角成分が1でそれ以外は0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# 指定値で埋める
np.full((2, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [30]:
# 範囲指定で均等割りデータの作成
np.linspace(0, 1, 5) # np.arange(0, 1.1, 0.25)と同じ

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
# 要素間の差
l = np.array([2, 2, 6, 1, 3])
np.diff(l) # 前後の差を出力

array([ 0,  4, -5,  2])

In [42]:
# 連結
b1 = np.array([[10], [20]])
np.concatenate([b, b1], axis = 1) # 列方向

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [43]:
np.hstack([b, b1])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [45]:
b2 = np.array([30, 60, 45])
b3 = np.vstack([b, b2]) # 行方向
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 60, 45]])

In [48]:
# 分割
first, second = np.hsplit(b3, [2])
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [49]:
second

array([[ 3],
       [ 6],
       [45]])

In [50]:
first1, second2 = np.vsplit(b3, [2])
first1

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
second2

array([[30, 60, 45]])

In [53]:
# 転置(行と列を入れ替えること)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
# 次元追加
a

array([1, 2, 3])

In [58]:
a[np.newaxis, :] # 行方向に追加

array([[1, 2, 3]])

In [60]:
a[:, np.newaxis] # 列方向に追加

array([[1],
       [2],
       [3]])

In [61]:
# グリッドデータの生成
# meshgrid関数は2次元上の点に対応する等高線やヒートマップなどを描くときに使用する
# x座標、y座標の配列から、それらを組み合わせてできるすべての点の座標データを生成する

m = np.arange(0, 4)
m

array([0, 1, 2, 3])

In [62]:
n = np.arange(4, 7)
n

array([4, 5, 6])

In [64]:
xx, yy = np.meshgrid(m, n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [65]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [66]:
# ユニバーサルファンクション
# Numpyの強烈なツールの一つ、配列要素内のデータを一括で変換

np.abs(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
e = np.linspace(-1, 1, 10)
np.sin(e)
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [74]:
a = np.arange(3)
np.log(a)

/Users/yukisakiyama/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718])

In [76]:
c = np.arange(1, 7).reshape((2, 3))
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [77]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [78]:
# ブロードキャスト
# 配列の内部データに直接演算などが行えるNumpyにとって非常に強烈な機能
a

array([0, 1, 2])

In [79]:
a + 10

array([10, 11, 12])

In [80]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
a + b

array([[1, 3, 5],
       [4, 6, 8]])

In [82]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [83]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [84]:
# 要素に0を含む割り算を実行すると無限大を表すinf
c / a

/Users/yukisakiyama/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [85]:
# 微妙な数値を足す
c / (a+1e-6)
# 0以外で割る要素は計算結果としてほぼ同じ数値、0で割る要素は非常に大きな数値

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

In [86]:
# ドット積
np.dot(b, a)

array([ 8, 17])

In [87]:
b @ a

array([ 8, 17])

In [88]:
# 判定・論理値
np.any(b > 0) # 要素の中にTrueが含まれているか確認

True

In [89]:
b[b > 0] # 条件に合致した新たな配列の作成

array([1, 2, 3, 4, 5, 6])

In [91]:
np.allclose(b, c, atol=10) # 誤差の範囲か確認

True

In [101]:
# 4-2.pandas(7, 17.5%)

# データ分析ツール、データの入手や加工に使われる
# シリーズ(Series)とデータフレーム(DataFrame)型

import pandas as pd

In [99]:
# Series = 1次元データ
# デフォルトのデータ型は'int64'

ser = pd.Series([10, 20, 30, 40])
ser

0    10
1    20
2    30
3    40
dtype: int64

In [103]:
# DataFrame = 2次元データ

df = pd.DataFrame(np.arange(6).reshape((3, 2)))
df

0  1
0  0  1
1  2  3
2  4  5

In [105]:
df.index = ["01", "02", "03"]
df.columns = ["A", "B"]
df

A  B
01  0  1
02  2  3
03  4  5

In [106]:
# データの抽出
# df.loc[インデックス名, カラム名]
# df.iloc[インデックス番号, カラム番号]

NameError: name 'インデックス名' is not defined

In [107]:
# データの読み込み

# pd.read_csv
# pd.read_excel

# pd.read_html(url)
# webサイトのHTML内にあるtable要素を抜き出す

# データの書き込み

# df.to_csv
# df.to_excel

# データの再利用

# df.to_pickle
# pd.read_pickle
# Pythonオブジェクトを直列化し、ファイルへの書き込み及び読み込みを可能

In [108]:
# データの整形

# df.query
# SQL構文のように条件を書き抽出

# .apply(pd.to_datetime)
# データ型変更

# df.sort_values(by="") 昇順
# df.sort_values(by="", ascending=False) 降順

#df_moved = pd.get_dummies(df.loc[:, "運動指数"], prefix="運動") get_dummiesで0,1、prefixで先頭の文字指定

# df.groupby(pd.Grouper(freq='M')).mean
# freq='M'で月ごとのデータ
# freq="W-SAT"で土曜日のデータ

In [109]:
# 欠損値の処理

# dropna
# 欠損値の行の削除

# fillna()
# fillna(method='ffill') 直前
# fillna(method= bfill') 直後
# .mode().iloc[0, :] 最頻値

In [110]:
# データ連結

# concat関数
# 列方向 axis=0
# 行方向 axis=1

In [111]:
# 統計データ

# .std() 標準偏差
# .std(ddof=0) 標本標準偏差

# describe() 統計量

In [112]:
# 相関係数

df.corr()

A    B
A  1.0  1.0
B  1.0  1.0

In [113]:
# データ変換

#pandasのDataFrameをNumpyの配列(ndarray)に変換
# .values

In [120]:
import pandas as pd
df = pd.DataFrame([[50, "a", False],[25, "b", True],[35, "c", True]])
df.index = ["01", "02", "03"]
df.columns = ["A", "B", "C"]
print(df)

def judge(arg):
    if arg <= 50:
        return "low"
    elif arg < 70:
        return "middle"
    else:
        return "high"

df.iloc[:, 2] = df.loc[:, "A"] * 2
print(df)
df.iloc[:, 1] = df.loc[:, "C"].apply(judge)
print(df)
_ = df["C"] < 80
df = df[_]
print(df)
print(df.iloc[1, 2], df.iloc[-1, 1])

     A  B      C
01  50  a  False
02  25  b   True
03  35  c   True
     A  B    C
01  50  a  100
02  25  b   50
03  35  c   70
     A     B    C
01  50  high  100
02  25   low   50
03  35  high   70
     A     B    C
01  50  high  100
02  25   low   50
03  35  high   70
     A     B   C
02  25   low  50
03  35  high  70
70 high


In [123]:
import numpy as np
import pandas as pd
np.random.seed(123)
dates = pd.date_range(start="2020-01-01", periods=31)
df = pd.DataFrame(np.random.randint(1, 10, 31), index=dates, columns=["rand"])
print(df)

df_year = pd.DataFrame(df.groupby(pd.Grouper(freq='W-MON')).sum(), columns=["rand"] )
print(df_year)

            rand
2020-01-01     3
2020-01-02     3
2020-01-03     7
2020-01-04     2
2020-01-05     4
2020-01-06     7
2020-01-07     2
2020-01-08     1
2020-01-09     2
2020-01-10     1
2020-01-11     1
2020-01-12     4
2020-01-13     5
2020-01-14     1
2020-01-15     1
2020-01-16     5
2020-01-17     2
2020-01-18     8
2020-01-19     4
2020-01-20     3
2020-01-21     5
2020-01-22     8
2020-01-23     3
2020-01-24     5
2020-01-25     9
2020-01-26     1
2020-01-27     8
2020-01-28     4
2020-01-29     5
2020-01-30     7
2020-01-31     2
            rand
2020-01-06    26
2020-01-13    16
2020-01-20    24
2020-01-27    39
2020-02-03    18
